spring:
  application:
    name: pet-service

server:
  port: 8085

config-service:
  url: http://localhost:8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/