spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:mysql://localhost:3314/petDB?useUnicode=true&characterEncoding=UTF-8
    username: tpnam
    password: 121831
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8101


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/