CREATE TABLE IF NOT EXISTS `angel` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `angel_index` INT NOT NULL,
    `angel_id` INT NOT NULL,
    `level` INT NOT NULL DEFAULT 1,
    `grade` INT NOT NULL DEFAULT 1,
    `exp` BIGINT NOT NULL DEFAULT 0,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `is_equipped` TINYINT(1) NOT NULL DEFAULT 0,
    `star_level` INT NOT NULL DEFAULT 0,
    `skill1_id` INT NULL,
    `skill1_level` INT NOT NULL DEFAULT 0,
    `skill2_id` INT NULL,
    `skill2_level` INT NOT NULL DEFAULT 0,
    `skill3_id` INT NULL,
    `skill3_level` INT NOT NULL DEFAULT 0,
    `skill4_id` INT NULL,
    `skill4_level` INT NOT NULL DEFAULT 0,
    `appearance_id` INT NULL,
    `appearance_level` INT NOT NULL DEFAULT 0,
    `evolution_stage` INT NOT NULL DEFAULT 0,
    `blessing_points` BIGINT NOT NULL DEFAULT 0,
    `name` VARCHAR(32) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_user_angel` (`user_id`, `angel_index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
