CREATE TABLE IF NOT EXISTS `rune` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `rune_index` INT NOT NULL,
    `rune_id` INT NOT NULL,
    `level` INT NOT NULL DEFAULT 1,
    `quality` INT NOT NULL DEFAULT 1,
    `star` INT NOT NULL DEFAULT 0,
    `is_equipped` TINYINT(1) NOT NULL DEFAULT 0,
    `equip_slot` INT NULL,
    `main_attr_type` INT NOT NULL DEFAULT 0,
    `main_attr_value` BIGINT NOT NULL DEFAULT 0,
    `sub_attr1_type` INT NULL,
    `sub_attr1_value` BIGINT NULL,
    `sub_attr2_type` INT NULL,
    `sub_attr2_value` BIGINT NULL,
    `sub_attr3_type` INT NULL,
    `sub_attr3_value` BIGINT NULL,
    `refinement_level` INT NOT NULL DEFAULT 0,
    `exp` BIGINT NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_user_rune` (`user_id`, `rune_index`),
    INDEX `idx_equipped` (`user_id`, `is_equipped`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
