server:
  port: 8110

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://localhost:3329/db_game_wallet
    username: tpnam
    password: 121831
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true