
services:
  # ===== USER / AUTH =====
  userdb:
    image: mysql:8.0
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-userdb
      MYSQL_DATABASE: userdb
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3308:3306"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - userdb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # ===== REPORT / SERVERINFO =====
  reportdb:
    image: mysql:8.0
    container_name: reportdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-reportDB
      MYSQL_DATABASE: report_game_h2
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3309:3306"
    volumes:
      - reportdb-data:/var/lib/mysql

  # ===== ROLE / MAINFB / GAMEWORLD / ARENA =====
  role_db:
    image: mysql:8.0
    container_name: role_db
    environment:
      MYSQL_ROOT_PASSWORD: admin-role_db
      MYSQL_DATABASE: game_role
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3310:3306"
    volumes:
      - role_db-data:/var/lib/mysql
      -
  redis:
    image: 'redis:7.2'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  userdb-data:
  reportdb-data:
  redis-data:
  role_db-data:

