
services:
  # ===== USER / AUTH =====
  userdb:
    image: mysql:8.0
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-userdb
      MYSQL_DATABASE: userdb
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3308:3306"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 5s
        timeout: 2s
        retries: 10
    volumes:
      - userdb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

 # session_db:
 #    image: mysql:8.0
 #    container_name: session_db
 #    environment:
  #     MYSQL_ROOT_PASSWORD: admin-session
  #     MYSQL_DATABASE: session_db
  #     MYSQL_USER: tpnam
  #     MYSQL_PASSWORD: 121831
 #    ports:
 #      - "3311:3306"
 #    volumes:
  #     - sessiondb-data:/var/lib/mysql

  # ===== REPORT / SERVERINFO =====
  reportdb:
    image: mysql:8.0
    container_name: reportdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-reportDB
      MYSQL_DATABASE: report_game_h2
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3309:3306"
    volumes:
      - reportdb-data:/var/lib/mysql

#  mysql_serverinfo:
#    image: mysql:8.0
#    container_name: mysql_serverinfo
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-serverinfo
#      MYSQL_DATABASE: game_serverInfor
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3310:3306"
#    volumes:
#      - serverinfo-data:/var/lib/mysql

  # ===== TASK =====
#  task_db:
#    image: mysql:8.0
#    container_name: task_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-task_db
 #     MYSQL_DATABASE: task_db
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3312:3306"
 #   volumes:
#      - task_db-data:/var/lib/mysql

  # ===== ITEM / BAG / BOX / EQUIP =====
#  db_item_service_DB:
#    image: mysql:8.0
#    container_name: db_item_service_DB
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-db_item_service
#      MYSQL_DATABASE: db_item_service
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3316:3306"
#    volumes:
#      - db_item_service-data:/var/lib/mysql
      
#  db_game_wallet_DB:
#    image: mysql:8.0
#    container_name: db_game_wallet_DB
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-db_game_wallet
#      MYSQL_DATABASE: db_game_wallet
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3329:3306"
#    volumes:
#      - db_game_wallet-data:/var/lib/mysql
        

#  db_equip_service:
#    image: mysql:8.0
#    container_name: db_equip_service
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-db_equip_service
#      MYSQL_DATABASE: db_equip_service
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3315:3306"
#    volumes:
#      - db_equip_service-data:/var/lib/mysql

#  bag_db:
#    image: mysql:8.0
#    container_name: bag_db
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-bag_db
#      MYSQL_DATABASE: db_bag_service
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3318:3306"
#    volumes:
#      - bag_db-data:/var/lib/mysql

#  box_db:
#    image: mysql:8.0
#    container_name: box_db
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-box_db
#      MYSQL_DATABASE: db_box_service
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3319:3306"
#    volumes:
#      - box_db-data:/var/lib/mysql

  # ===== SHOP / CFG =====
#  shop_db:
#    image: mysql:8.0
#    container_name: shop_db
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-shop_db
#      MYSQL_DATABASE: game_shop
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3320:3306"
#    volumes:
#      - shop_db-data:/var/lib/mysql

 # cfg_db:
  #  image: mysql:8.0
 #   container_name: cfg_db
  #  environment:
  #    MYSQL_ROOT_PASSWORD: admin-cfg_db
  #    MYSQL_DATABASE: game_cfg
  #    MYSQL_USER: tpnam
  #    MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3323:3306"
 #   volumes:
 #     - cfg_db-data:/var/lib/mysql

  # ===== MAIL / GIFT =====
 # mail_db:
 #   image: mysql:8.0
 #   container_name: mail_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-mail_db
 #     MYSQL_DATABASE: game_mail
  #    MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3321:3306"
 #   volumes:
 #     - mail_db-data:/var/lib/mysql

#  gift_db:
#    image: mysql:8.0
#    container_name: gift_db
#    environment:
#      MYSQL_ROOT_PASSWORD: admin-gift_db
#      MYSQL_DATABASE: gift_service
#      MYSQL_USER: tpnam
#      MYSQL_PASSWORD: 121831
#    ports:
#      - "3322:3306"
#    volumes:
#      - gift_db-data:/var/lib/mysql

  # ===== ROLE / MAINFB / GAMEWORLD / ARENA =====
  role_db:
    image: mysql:8.0
    container_name: role_db
    environment:
      MYSQL_ROOT_PASSWORD: admin-role_db
      MYSQL_DATABASE: game_role
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3310:3306"
    volumes:
      - role_db-data:/var/lib/mysql


 # mainfb_db:
 #   image: mysql:8.0
 #   container_name: mainfb_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-mainfb_db
 #     MYSQL_DATABASE: game_mainfb
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3325:3306"
 #   volumes:
 #     - mainfb_db-data:/var/lib/mysql

 # gameworld_db:
 #   image: mysql:8.0
 #   container_name: gameworld_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-gameworld_db
 #     MYSQL_DATABASE: gameworld
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3326:3306"
 #   volumes:
 #     - gameworld_db-data:/var/lib/mysql

 # arena_db:
 #   image: mysql:8.0
 #   container_name: arena_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-arena_db
 #     MYSQL_DATABASE: game_arena
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3327:3306"
 #   volumes:
 #     - arena_db-data:/var/lib/mysql

  # ===== GLOBAL SERVER / FASHION / PET =====
 # globalserver_service_db:
 #   image: mysql:8.0
 #   container_name: globalserver_service_db
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-globalserver_service_db
 #     MYSQL_DATABASE: globalserver_service_db
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3317:3306"
 #   volumes:
 #     - globalserver_service_db-data:/var/lib/mysql

 # shizhuangdb:
 #   image: mysql:8.0
 #   container_name: shizhuangdb
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-shizhuangdb
 #     MYSQL_DATABASE: shizhuangdb
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3313:3306"
 #   volumes:
 #     - shizhuangdb-data:/var/lib/mysql

 # petDB:
 #   image: mysql:8.0
 #   container_name: petDB
 #   environment:
 #     MYSQL_ROOT_PASSWORD: admin-petDB
 #     MYSQL_DATABASE: petDB
 #     MYSQL_USER: tpnam
 #     MYSQL_PASSWORD: 121831
 #   ports:
 #     - "3314:3306"
 #   volumes:
 #     - petDB-data:/var/lib/mysql

  # ===== Infra: Kafka / Redis / ELK =====
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - redis

  redis:
    image: 'redis:7.2'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  kafka-data:
  userdb-data:
  reportdb-data:
 # serverinfo-data:
 # sessiondb-data:
 # task_db-data:
 # db_equip_service-data:
 # petDB-data:
 # db_item_service-data:
 # globalserver_service_db-data:
 # shizhuangdb-data:
  redis-data:
#  bag_db-data:
#  box_db-data:
#  shop_db-data:
 # cfg_db-data:
 # mail_db-data:
#  gift_db-data:
  role_db-data:
 # db_game_wallet-data:
 # mainfb_db-data:
 # gameworld_db-data:
 # arena_db-data:
