services:
  # ===== USER / AUTH =====
  userdb:
    image: mysql:8.0
    container_name: userdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-userdb
      MYSQL_DATABASE: userdb
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3308:3306"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - userdb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # ===== REPORT / SERVERINFO =====
  reportdb:
    image: mysql:8.0
    container_name: reportdb
    environment:
      MYSQL_ROOT_PASSWORD: admin-reportDB
      MYSQL_DATABASE: report_game_h2
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - reportdb-data:/var/lib/mysql

  # ===== ROLE / MAINFB / GAMEWORLD / ARENA =====
  role_db:
    image: mysql:8.0
    container_name: role_db
    environment:
      MYSQL_ROOT_PASSWORD: admin-role_db
      MYSQL_DATABASE: game_role
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - role_db-data:/var/lib/mysql

  bag_db:
    image: mysql:8.0
    container_name: bag_db
    environment:
      MYSQL_ROOT_PASSWORD: admin-bag_db
      MYSQL_DATABASE: db_bag
      MYSQL_USER: tpnam
      MYSQL_PASSWORD: 121831
    ports:
      - "3311:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - bag_db-data:/var/lib/mysql

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"   # Host connect qua cổng này
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka-data:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka

volumes:
  kafka-data:
  userdb-data:
  reportdb-data:
  redis-data:
  role_db-data:
  bag_db-data:
