server:
  port: 8540
spring:
  profiles:
    active: local  # Default to local profile
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# gRPC Server
grpc:
  server:
    port: 9540
    
file:
  upload-dir: ./uploads
  base-url: http://localhost:8540/files
