spring:
  application:
    name: world-service

server:
  port: 8084

config-service:
  url: http://localhost:8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/