server:
  port: 8096

spring:
  application:
    name: session-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      # Nếu bạn dùng URL, nó sẽ override host/port/user/pass/database
      # url: ${REDIS_URL:}
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0

jwt:
  issuer: "SouthMillion"
  secret: ${JWT_SECRET:xxx}
  access-ttl-seconds: 900
  refresh-ttl-seconds: 604800
  rotate-refresh: true

ratelimit:
  enabled: true
  window-seconds: 60
  login-limit: 10
  refresh-limit: 60
  generic-limit: 300

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/