
//!<MsgId:2130
message PB_CSAngelReq {//!<2130 操作
	optional int32	req_type = 1;
	optional int32	param = 2;
	optional int32	param2 = 3;
}

message PB_AngelAppearanceData{
	optional int32 id = 1;
	optional int32 level = 2;
}

//!<MsgId:2131
message PB_SCAngelInfo {//!<2131 天使信息
	optional int32	angel_level = 1;					//!< 等级
	optional int32	angel_grade = 2;					//!< 阶级
	repeated int32	angel_equip_id = 3;					//!< 装备id
	optional int32	use_appearance = 4;					//!< 使用的皮肤
	repeated PB_AngelAppearanceData appearance_data = 5;//!< 皮肤列表
}

//!<MsgId:2132
message PB_SCAngelOpRet {//!<2132 操作回调
	optional int32	ret_type = 1;
	optional int32	param1 = 2;
	optional int32	param2 = 3;
}