server:
  port: 8095

spring:
  application:
    name: serverInfo-service
  datasource:
    url: jdbc:mysql://localhost:3310/game_serverInfor?serverTimezone=UTC
    username: tpnam
    password: 121831
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/