server:
  port: 8087

spring:
  application:
    name: config-service
  threads:
    virtual:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true         # dev máy cá nhân nên bật cho chắc
    # instance-id tuỳ chọn để dễ nhận diện trong dashboard:
    instance-id: "${spring.application.name}:${server.port}"

config:
  mode: classpath  # classpath | filesystem
  root: ""         # nếu mode=filesystem, trỏ tới thư mục chứa "config/"
  cache:
    l1-enabled: true
    l1-spec: "maximumSize=5000,expireAfterAccess=10m"