server:
  port: 8091
spring:
  application:
    name: config-service
  threads:
    virtual:
      enabled: true   # Java 21 virtual threads cho MVC

management:
  endpoints:
    web.exposure.include: health,info,env,metrics

app:
  config:
    mode: classpath                # hoặc filesystem
    classpath-root: config         # resources/config/...
    fs-root: /opt/app/config       # nếu dùng filesystem
    cache-ttl-sec: 300
    cache-max-size: 2000
    public-cache-control: max-age=60, public
    l2:
      enabled: true
      dir: /tmp/config-l2-cache
      max-bytes-per-entry: 10485760

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/