spring:
  application:
    name: config-service
  data:
    redis:
      host: localhost
      port: 6379
# Nếu có password:
# spring.redis.password=yourpassword

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083