spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3316/db_item_service?useUnicode=true&characterEncoding=UTF-8
    username: tpnam
    password: 121831
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8102


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

